export const products = [
  {
    id: 41,
    title: 'NIGHT SUIT',
    description: 'NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.',
    price: 55,
    discountPercentage: 15.05,
    rating: 4.65,
    stock: 1,
    brand: 'RED MICKY MOUSE..',
    category: 'womens-dresses',
    thumbnail: 'https://i.dummyjson.com/data/products/41/thumbnail.webp',
    images: [
      'https://i.dummyjson.com/data/products/41/1.jpg',
      'https://i.dummyjson.com/data/products/41/2.webp',
      'https://i.dummyjson.com/data/products/41/3.jpg',
      'https://i.dummyjson.com/data/products/41/4.jpg',
      'https://i.dummyjson.com/data/products/41/thumbnail.webp',
    ],
  },
  {
    id: 42,
    title: 'Stiched Kurta plus trouser',
    description: 'FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN',
    price: 80,
    discountPercentage: 15.37,
    rating: 4.05,
    stock: 4,
    brand: 'Digital Printed',
    category: 'womens-dresses',
    thumbnail: 'https://i.dummyjson.com/data/products/42/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/42/1.png',
      'https://i.dummyjson.com/data/products/42/2.png',
      'https://i.dummyjson.com/data/products/42/3.png',
      'https://i.dummyjson.com/data/products/42/4.jpg',
      'https://i.dummyjson.com/data/products/42/thumbnail.jpg',
    ],
  },
  {
    id: 43,
    title: 'frock gold printed',
    description: 'Ghazi fabric long frock gold printed ready to wear stitched collection (G992)',
    price: 600,
    discountPercentage: 15.55,
    rating: 4.31,
    stock: 150,
    brand: 'Ghazi Fabric',
    category: 'womens-dresses',
    thumbnail: 'https://i.dummyjson.com/data/products/43/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/43/1.jpg',
      'https://i.dummyjson.com/data/products/43/2.jpg',
      'https://i.dummyjson.com/data/products/43/3.jpg',
      'https://i.dummyjson.com/data/products/43/4.jpg',
      'https://i.dummyjson.com/data/products/43/thumbnail.jpg',
    ],
  },
  {
    id: 46,
    title: 'women\'s shoes',
    description: 'Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber',
    price: 40,
    discountPercentage: 16.96,
    rating: 4.14,
    stock: 72,
    brand: 'IELGY fashion',
    category: 'womens-shoes',
    thumbnail: 'https://i.dummyjson.com/data/products/46/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/46/1.webp',
      'https://i.dummyjson.com/data/products/46/2.jpg',
      'https://i.dummyjson.com/data/products/46/3.jpg',
      'https://i.dummyjson.com/data/products/46/4.jpg',
      'https://i.dummyjson.com/data/products/46/thumbnail.jpg',
    ],
  },
  {
    id: 47,
    title: 'Sneaker shoes',
    description: 'Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women',
    price: 120,
    discountPercentage: 10.37,
    rating: 4.19,
    stock: 50,
    brand: 'Synthetic Leather',
    category: 'womens-shoes',
    thumbnail: 'https://i.dummyjson.com/data/products/47/thumbnail.jpeg',
    images: [
      'https://i.dummyjson.com/data/products/47/1.jpg',
      'https://i.dummyjson.com/data/products/47/2.jpg',
      'https://i.dummyjson.com/data/products/47/3.jpg',
      'https://i.dummyjson.com/data/products/47/thumbnail.jpeg',
    ],
  },
  {
    id: 48,
    title: 'Women Strip Heel',
    description: 'Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped',
    price: 40,
    discountPercentage: 10.83,
    rating: 4.02,
    stock: 25,
    brand: 'Sandals Flip Flops',
    category: 'womens-shoes',
    thumbnail: 'https://i.dummyjson.com/data/products/48/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/48/1.jpg',
      'https://i.dummyjson.com/data/products/48/2.jpg',
      'https://i.dummyjson.com/data/products/48/3.jpg',
      'https://i.dummyjson.com/data/products/48/4.jpg',
      'https://i.dummyjson.com/data/products/48/thumbnail.jpg',
    ],
  },
  {
    id: 51,
    title: 'half sleeves T shirts',
    description: 'Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands',
    price: 23,
    discountPercentage: 12.76,
    rating: 4.26,
    stock: 132,
    brand: 'Vintage Apparel',
    category: 'mens-shirts',
    thumbnail: 'https://i.dummyjson.com/data/products/51/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/51/1.png',
      'https://i.dummyjson.com/data/products/51/2.jpg',
      'https://i.dummyjson.com/data/products/51/3.jpg',
      'https://i.dummyjson.com/data/products/51/thumbnail.jpg',
    ],
  },
  {
    id: 52,
    title: 'FREE FIRE T Shirt',
    description: 'quality and professional print - It doesn\'t just look high quality, it is high quality.',
    price: 10,
    discountPercentage: 14.72,
    rating: 4.52,
    stock: 128,
    brand: 'FREE FIRE',
    category: 'mens-shirts',
    thumbnail: 'https://i.dummyjson.com/data/products/52/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/52/1.png',
      'https://i.dummyjson.com/data/products/52/2.png',
      'https://i.dummyjson.com/data/products/52/3.jpg',
      'https://i.dummyjson.com/data/products/52/4.jpg',
      'https://i.dummyjson.com/data/products/52/thumbnail.jpg',
    ],
  },
  {
    id: 53,
    title: 'printed high quality T shirts',
    description: 'Brand: vintage Apparel ,Export quality',
    price: 35,
    discountPercentage: 7.54,
    rating: 4.89,
    stock: 6,
    brand: 'Vintage Apparel',
    category: 'mens-shirts',
    thumbnail: 'https://i.dummyjson.com/data/products/53/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/53/1.webp',
      'https://i.dummyjson.com/data/products/53/2.jpg',
      'https://i.dummyjson.com/data/products/53/3.jpg',
      'https://i.dummyjson.com/data/products/53/4.jpg',
      'https://i.dummyjson.com/data/products/53/thumbnail.jpg',
    ],
  },
  {
    id: 56,
    title: 'Sneakers Joggers Shoes',
    description: 'Gender: Men , Colors: Same as DisplayedCondition: 100% Brand New',
    price: 40,
    discountPercentage: 12.57,
    rating: 4.38,
    stock: 6,
    brand: 'Sneakers',
    category: 'mens-shoes',
    thumbnail: 'https://i.dummyjson.com/data/products/56/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/56/1.jpg',
      'https://i.dummyjson.com/data/products/56/2.jpg',
      'https://i.dummyjson.com/data/products/56/3.jpg',
      'https://i.dummyjson.com/data/products/56/4.jpg',
      'https://i.dummyjson.com/data/products/56/5.jpg',
      'https://i.dummyjson.com/data/products/56/thumbnail.jpg',
    ],
  },
  {
    id: 57,
    title: 'Loafers for men',
    description: 'Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.',
    price: 47,
    discountPercentage: 10.91,
    rating: 4.91,
    stock: 20,
    brand: 'Rubber',
    category: 'mens-shoes',
    thumbnail: 'https://i.dummyjson.com/data/products/57/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/57/1.jpg',
      'https://i.dummyjson.com/data/products/57/2.jpg',
      'https://i.dummyjson.com/data/products/57/3.jpg',
      'https://i.dummyjson.com/data/products/57/4.jpg',
      'https://i.dummyjson.com/data/products/57/thumbnail.jpg',
    ],
  },
  {
    id: 58,
    title: 'formal offices shoes',
    description: 'Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe ,Outsole Material: Rubber',
    price: 57,
    discountPercentage: 12,
    rating: 4.41,
    stock: 68,
    brand: 'The Warehouse',
    category: 'mens-shoes',
    thumbnail: 'https://i.dummyjson.com/data/products/58/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/58/1.jpg',
      'https://i.dummyjson.com/data/products/58/2.jpg',
      'https://i.dummyjson.com/data/products/58/3.jpg',
      'https://i.dummyjson.com/data/products/58/4.jpg',
      'https://i.dummyjson.com/data/products/58/thumbnail.jpg',
    ],
  },
  {
    id: 61,
    title: 'Leather Straps Wristwatch',
    description: 'Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar',
    price: 120,
    discountPercentage: 7.14,
    rating: 4.63,
    stock: 91,
    brand: 'Naviforce',
    category: 'mens-watches',
    thumbnail: 'https://i.dummyjson.com/data/products/61/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/61/1.jpg',
      'https://i.dummyjson.com/data/products/61/2.png',
      'https://i.dummyjson.com/data/products/61/3.jpg',
    ],
  },
  {
    id: 62,
    title: 'Waterproof Leather Brand Watch',
    description: 'Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours',
    price: 46,
    discountPercentage: 3.15,
    rating: 4.05,
    stock: 95,
    brand: 'SKMEI 9117',
    category: 'mens-watches',
    thumbnail: 'https://i.dummyjson.com/data/products/62/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/62/1.jpg',
      'https://i.dummyjson.com/data/products/62/2.jpg',
    ],
  },
  {
    id: 63,
    title: 'Royal Blue Premium Watch',
    description: 'Men Silver Chain Royal Blue Premium Watch Latest Analog Watch',
    price: 50,
    discountPercentage: 2.56,
    rating: 4.89,
    stock: 142,
    brand: 'SKMEI 9117',
    category: 'mens-watches',
    thumbnail: 'https://i.dummyjson.com/data/products/63/thumbnail.webp',
    images: [
      'https://i.dummyjson.com/data/products/63/1.jpg',
      'https://i.dummyjson.com/data/products/63/2.jpg',
      'https://i.dummyjson.com/data/products/63/3.png',
      'https://i.dummyjson.com/data/products/63/4.jpeg',
    ],
  },
  {
    id: 66,
    title: 'Steel Analog Couple Watches',
    description: 'Elegant design, Stylish ,Unique & Trendy,Comfortable wear',
    price: 35,
    discountPercentage: 3.23,
    rating: 4.79,
    stock: 24,
    brand: 'Eastern Watches',
    category: 'womens-watches',
    thumbnail: 'https://i.dummyjson.com/data/products/66/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/66/1.jpg',
      'https://i.dummyjson.com/data/products/66/2.jpg',
      'https://i.dummyjson.com/data/products/66/3.jpg',
      'https://i.dummyjson.com/data/products/66/4.JPG',
      'https://i.dummyjson.com/data/products/66/thumbnail.jpg',
    ],
  },
  {
    id: 67,
    title: 'Fashion Magnetic Wrist Watch',
    description: 'Buy this awesome  The product is originally manufactured by the company and it\'s a top selling product with a very reasonable',
    price: 60,
    discountPercentage: 16.69,
    rating: 4.03,
    stock: 46,
    brand: 'Eastern Watches',
    category: 'womens-watches',
    thumbnail: 'https://i.dummyjson.com/data/products/67/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/67/1.jpg',
      'https://i.dummyjson.com/data/products/67/2.jpg',
      'https://i.dummyjson.com/data/products/67/3.jpg',
      'https://i.dummyjson.com/data/products/67/4.jpg',
      'https://i.dummyjson.com/data/products/67/thumbnail.jpg',
    ],
  },
  {
    id: 68,
    title: 'Stylish Luxury Digital Watch',
    description: 'Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls',
    price: 57,
    discountPercentage: 9.03,
    rating: 4.55,
    stock: 77,
    brand: 'Luxury Digital',
    category: 'womens-watches',
    thumbnail: 'https://i.dummyjson.com/data/products/68/thumbnail.webp',
    images: [
      'https://i.dummyjson.com/data/products/68/1.jpg',
      'https://i.dummyjson.com/data/products/68/2.jpg',
    ],
  },
  {
    id: 81,
    title: 'Round Silver Frame Sun Glasses',
    description: 'A pair of sunglasses can protect your eyes from being hurt. For car driving, vacation travel, outdoor activities, social gatherings,',
    price: 19,
    discountPercentage: 10.1,
    rating: 4.94,
    stock: 78,
    brand: 'Designer Sun Glasses',
    category: 'sunglasses',
    thumbnail: 'https://i.dummyjson.com/data/products/81/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/81/1.jpg',
      'https://i.dummyjson.com/data/products/81/2.jpg',
      'https://i.dummyjson.com/data/products/81/3.jpg',
      'https://i.dummyjson.com/data/products/81/4.webp',
      'https://i.dummyjson.com/data/products/81/thumbnail.jpg',
    ],
  },
  {
    id: 82,
    title: 'Kabir Singh Square Sunglass',
    description: 'Orignal Metal Kabir Singh design 2020 Sunglasses Men Brand Designer Sun Glasses Kabir Singh Square Sunglass',
    price: 50,
    discountPercentage: 15.6,
    rating: 4.62,
    stock: 78,
    brand: 'Designer Sun Glasses',
    category: 'sunglasses',
    thumbnail: 'https://i.dummyjson.com/data/products/82/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/82/1.jpg',
      'https://i.dummyjson.com/data/products/82/2.webp',
      'https://i.dummyjson.com/data/products/82/3.jpg',
      'https://i.dummyjson.com/data/products/82/4.jpg',
      'https://i.dummyjson.com/data/products/82/thumbnail.jpg',
    ],
  },
  {
    id: 83,
    title: 'Wiley X Night Vision Yellow Glasses',
    description: 'Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches',
    price: 30,
    discountPercentage: 6.33,
    rating: 4.97,
    stock: 115,
    brand: 'mastar watch',
    category: 'sunglasses',
    thumbnail: 'https://i.dummyjson.com/data/products/83/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/83/1.jpg',
      'https://i.dummyjson.com/data/products/83/2.jpg',
      'https://i.dummyjson.com/data/products/83/3.jpg',
      'https://i.dummyjson.com/data/products/83/4.jpg',
      'https://i.dummyjson.com/data/products/83/thumbnail.jpg',
    ],
  },
];
